/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/Bonzo.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Bonzo.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Male_Xter_New" rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
        <group name="Armature" position={[0, 2.963, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.17}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="body" geometry={nodes.body.geometry} material={materials.body} skeleton={nodes.body.skeleton} />
          <skinnedMesh name="Body_band" geometry={nodes.Body_band.geometry} material={materials.Body_band} skeleton={nodes.Body_band.skeleton} />
          <skinnedMesh name="Cap" geometry={nodes.Cap.geometry} material={materials.Cap} skeleton={nodes.Cap.skeleton} />
          <skinnedMesh name="Eye_shine" geometry={nodes.Eye_shine.geometry} material={materials.Eye_shine} skeleton={nodes.Eye_shine.skeleton} />
          <skinnedMesh name="Eyes" geometry={nodes.Eyes.geometry} material={materials.Eyes} skeleton={nodes.Eyes.skeleton} />
          <skinnedMesh name="Flys" geometry={nodes.Flys.geometry} material={materials.Flys} skeleton={nodes.Flys.skeleton} />
          <skinnedMesh name="Hair_long" geometry={nodes.Hair_long.geometry} material={materials.Hair_long} skeleton={nodes.Hair_long.skeleton} />
          <skinnedMesh name="Head" geometry={nodes.Head.geometry} material={materials.Head} skeleton={nodes.Head.skeleton} />
          <skinnedMesh name="trouser_hook" geometry={nodes.trouser_hook.geometry} material={materials.trouser_hook} skeleton={nodes.trouser_hook.skeleton} />
          <skinnedMesh name="wrapper" geometry={nodes.wrapper.geometry} material={materials.wrapper} skeleton={nodes.wrapper.skeleton} />
          <skinnedMesh name="Wrappers1" geometry={nodes.Wrappers1.geometry} material={materials.Wrappers1} skeleton={nodes.Wrappers1.skeleton} />
        </group>
        <group name="Male_Xter_New001" position={[0.229, 26.592, 16.905]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="Armature001" position={[0.229, 26.592, 16.905]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_1} />
          <skinnedMesh name="body001" geometry={nodes.body001.geometry} material={materials['body.001']} skeleton={nodes.body001.skeleton} />
          <skinnedMesh name="Body_band001" geometry={nodes.Body_band001.geometry} material={materials['Body_band.001']} skeleton={nodes.Body_band001.skeleton} />
          <skinnedMesh name="Cap001" geometry={nodes.Cap001.geometry} material={materials['Cap.001']} skeleton={nodes.Cap001.skeleton} />
          <skinnedMesh name="Eye_shine001" geometry={nodes.Eye_shine001.geometry} material={materials['Eye_shine.001']} skeleton={nodes.Eye_shine001.skeleton} />
          <skinnedMesh name="Eyes001" geometry={nodes.Eyes001.geometry} material={materials['Eyes.001']} skeleton={nodes.Eyes001.skeleton} />
          <skinnedMesh name="Flys001" geometry={nodes.Flys001.geometry} material={materials['Flys.001']} skeleton={nodes.Flys001.skeleton} />
          <skinnedMesh name="Hair_long001" geometry={nodes.Hair_long001.geometry} material={materials['Hair_long.001']} skeleton={nodes.Hair_long001.skeleton} />
          <skinnedMesh name="Head001" geometry={nodes.Head001.geometry} material={materials['Head.001']} skeleton={nodes.Head001.skeleton} />
          <skinnedMesh name="trouser_hook001" geometry={nodes.trouser_hook001.geometry} material={materials['trouser_hook.001']} skeleton={nodes.trouser_hook001.skeleton} />
          <skinnedMesh name="wrapper001" geometry={nodes.wrapper001.geometry} material={materials['wrapper.001']} skeleton={nodes.wrapper001.skeleton} />
          <skinnedMesh name="Wrappers1001" geometry={nodes.Wrappers1001.geometry} material={materials['Wrappers1.001']} skeleton={nodes.Wrappers1001.skeleton} />
        </group>
        <mesh name="Torus" geometry={nodes.Torus.geometry} material={nodes.Torus.material} position={[0.069, 29.364, -0.069]} rotation={[0, 0, -0.199]} scale={10} />
        <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={nodes.Torus001.material} position={[0.069, 29.364, -0.069]} rotation={[-0.046, 0.159, 0.283]} scale={13.49} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.654, 31.013, -0.566]} scale={0.25} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-10.214, 26.354, 8.105]} scale={1.66} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[9.199, 27.493, -2.676]} />
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[-10.428, 28.768, 5.695]} scale={0.27} />
        <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[-12.245, 25.499, 8.335]} scale={0.17} />
        <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[-9.152, 25.154, 10.158]} scale={0.58} />
        <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[0.209, 26.354, 16.82]} scale={[1.66, 0.314, 1.66]} />
        <mesh name="Surf" geometry={nodes.Surf.geometry} material={materials.Surf} position={[4505.708, 1712.532, -2769.967]} rotation={[0, Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bonzo.glb')
